### ISSUE TITLE
add support pycharm?

### ISSUE THREAD

**Issue by zhaoqingqing** [xfcy/CopyThePath#2]
pycharm community cannot install.

how to build by self?
when i try run in idea ,get error:Could not resolve org.jetbrains.intellij.plugins:gradle-intellij-plugin:1.6.0.

**Comment by xfcy** [comment]
I'll test for pycharm community soon, which version of pycharm?

**Comment by zhaoqingqing** [comment]
2022.3

**Comment by xfcy** [comment]
I tried install from marketplace, there are no problem work with pycharm 2022.3, IntelliJ Plugin Verifier's result is also Compatible.

To avoid the error you get, you can try updating the version of the org.jetbrains.intellij plugin in build.gradle.kts up to date.

If there is more information, such as error messages during installation, please submit them together so that I can locate the problem and fix it in time.

Thanks for your contribution :)
